### ISSUE TITLE
恩，根本就跑不起来

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [lguipeng/Notes#11]
锤子T1

FATAL EXCEPTION: main
                                                                    Process: com.lguipeng.notes, PID: 15175
                                                                    java.lang.VerifyError: com/lguipeng/notes/mvp/presenters/impl/MainPresenter
                                                                        at com.lguipeng.notes.mvp.presenters.impl.MainPresenter_Factory.get(MainPresenter_Factory.java:35)
                                                                        at com.lguipeng.notes.mvp.presenters.impl.MainPresenter_Factory.get(MainPresenter_Factory.java:12)
                                                                        at com.lguipeng.notes.ui.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:26)
                                                                        at com.lguipeng.notes.ui.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:8)
                                                                        at com.lguipeng.notes.injector.component.DaggerActivityComponent.inject(DaggerActivityComponent.java:86)
                                                                        at com.lguipeng.notes.ui.MainActivity.initializeDependencyInjector(MainActivity.java:85)
                                                                        at com.lguipeng.notes.ui.BaseActivity.onCreate(BaseActivity.java:32)
                                                                        at com.lguipeng.notes.ui.MainActivity.onCreate(MainActivity.java:69)
                                                                        at android.app.Activity.performCreate(Activity.java:5242)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:145)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1206)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by lguipeng** [comment]
已经解决了呀，看 issue #6

**Comment by ZhaoKaiQiang** [comment]
apk文件夹下面的apk文件安装上也是Crash，Nexus 6机器装上也是Crash，无解

**Comment by lguipeng** [comment]
apk下不一定是最新的，你更新下代码试下打下包，以前在4.4有这个问题， 6.0也是有个方法冲突了，现在都改了，6.0 4.4我都试过了，主要自己用的机子是5.1，所以。。。
或者你去豌豆荚下个最新的，看下有没有问题
