### ISSUE TITLE
 导入这个工程 运行 报错

### ISSUE THREAD

**Issue by lanzf** [lguipeng/Notes#3]
刚开始整android studio 把环境搭起来后 导入这个工程 运行 报错

07-29 15:33:53.160    1815-1815/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.lguipeng.notes, PID: 1815
    java.lang.RuntimeException: Unable to instantiate application com.lguipeng.notes.App: java.lang.ClassNotFoundException: Didn't find class "com.lguipeng.notes.App" on path: DexPathList[[zip file "/data/app/com.lguipeng.notes-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lguipeng.notes.App" on path: DexPathList[[zip file "/data/app/com.lguipeng.notes-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at android.app.Instrumentation.newApplication(Instrumentation.java:980)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
            at android.app.ActivityThread.access$1500(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    Suppressed: java.lang.ClassNotFoundException: com.lguipeng.notes.App
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 13 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
07-29 15:36:34.167    1815-1826/? W/art﹕ Suspending all threads took: 20.998ms
07-29 15:38:53.184    1815-1815/? I/Process﹕ Sending signal. PID: 1815 SIG: 9

**Comment by lanzf** [comment]
clean 就好了   晕
