### ISSUE TITLE
编译安装到手机上,不能打开程序,报如下错误

### ISSUE THREAD

**Issue by JavanZhu** [lguipeng/Notes#6]
通过android studio1.4编译安装, 能够安装到手机上,但是点击应用程序图标就出现如下错误:

```
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime: FATAL EXCEPTION: main
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime: Process: com.lguipeng.notes, PID: 4638
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime: java.lang.VerifyError: com/lguipeng/notes/mvp/presenters/impl/MainPresenter
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.mvp.presenters.impl.MainPresenter_Factory.get(MainPresenter_Factory.java:35)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.mvp.presenters.impl.MainPresenter_Factory.get(MainPresenter_Factory.java:12)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.ui.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:26)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.ui.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:8)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.injector.component.DaggerActivityComponent.inject(DaggerActivityComponent.java:86)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.ui.MainActivity.initializeDependencyInjector(MainActivity.java:85)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.ui.BaseActivity.onCreate(BaseActivity.java:32)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.lguipeng.notes.ui.MainActivity.onCreate(MainActivity.java:69)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5248)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:141)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5113)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-03 17:46:49.038 4638-4638/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by lguipeng** [comment]
没有遇过这种情况，你可以看下这个http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror
